
version: 2

sources:
  - name: data
    database: study-341002
    tables:
      - name: legislaturas

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: legislaturas_cleaned
    description: "A cleaned version of the legislaturas table"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
      - name: name
        description: "The name of the legislatura"
        tests:
          - not_null
      - name: start_date
        description: "The start date of the legislatura"
        tests:
          - not_null
      - name: end_date
        description: "The end date of the legislatura"
      - name: status
        description: "The status of the legislatura"
        tests:
          - accepted_values:
              values: ["active", "inactive"]