
version: 2

sources:
  - name: data
    database: study-341002
    tables:
      - name: legislaturas

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"

  - name: legislaturas_cleaned
    description: "A cleaned version of the legislaturas table"
    columns:
      - name: id_legislatura
        description: "The primary key for this table"
        tests:
          - unique
      - name: sigla_casa
        description: "The name of the legislatura"
        tests:
          - not_null
      - name: num_legislatura
        description: "The start date of the legislatura"
        tests:
          - not_null
      - name: data_inicio
        description: "The end date of the legislatura"